load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "copy_file_lib",
    srcs = ["main.go"],
    importpath = "github.com/aspect-build/bazel-lib/tools/copy_file",
    visibility = ["//visibility:public"],
    deps = [
        "//tools/common",
        "//tools/proto",
        "@org_golang_google_protobuf//encoding/protowire",
        "@org_golang_google_protobuf//proto",
    ],
)

go_binary(
    name = "copy_file",
    embed = [":copy_file_lib"],
    visibility = ["//visibility:public"],
)
