// Copyright 2015 The Bazel Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/worker_protocol.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An input file.
type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The path in the file system where to read this input artifact from. This is
	// either a path relative to the execution root (the worker process is
	// launched with the working directory set to the execution root), or an
	// absolute path.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// A hash-value of the contents. The format of the contents is unspecified and
	// the digest should be treated as an opaque token. This can be empty in some
	// cases.
	Digest []byte `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_worker_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_proto_worker_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Input) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

// This represents a single work unit that Blaze sends to the worker.
type WorkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arguments []string `protobuf:"bytes,1,rep,name=arguments,proto3" json:"arguments,omitempty"`
	// The inputs that the worker is allowed to read during execution of this
	// request.
	Inputs []*Input `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// Each WorkRequest must have either a unique
	// request_id or request_id = 0. If request_id is 0, this WorkRequest must be
	// processed alone (singleplex), otherwise the worker may process multiple
	// WorkRequests in parallel (multiplexing). As an exception to the above, if
	// the cancel field is true, the request_id must be the same as a previously
	// sent WorkRequest. The request_id must be attached unchanged to the
	// corresponding WorkResponse. Only one singleplex request may be sent to a
	// worker at a time.
	RequestId int32 `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// EXPERIMENTAL: When true, this is a cancel request, indicating that a
	// previously sent WorkRequest with the same request_id should be cancelled.
	// The arguments and inputs fields must be empty and should be ignored.
	Cancel bool `protobuf:"varint,4,opt,name=cancel,proto3" json:"cancel,omitempty"`
	// Values greater than 0 indicate that the worker may output extra debug
	// information to stderr (which will go into the worker log). Setting the
	// --worker_verbose flag for Bazel makes this flag default to 10.
	Verbosity int32 `protobuf:"varint,5,opt,name=verbosity,proto3" json:"verbosity,omitempty"`
	// The relative directory inside the workers working directory where the
	// inputs and outputs are placed, for sandboxing purposes. For singleplex
	// workers, this is unset, as they can use their working directory as sandbox.
	// For multiplex workers, this will be set when the
	// --experimental_worker_multiplex_sandbox flag is set _and_ the execution
	// requirements for the worker includes 'supports-multiplex-sandbox'.
	// The paths in `inputs` will not contain this prefix, but the actual files
	// will be placed/must be written relative to this directory. The worker
	// implementation is responsible for resolving the file paths.
	SandboxDir string `protobuf:"bytes,6,opt,name=sandbox_dir,json=sandboxDir,proto3" json:"sandbox_dir,omitempty"`
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_worker_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *WorkRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *WorkRequest) GetInputs() []*Input {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *WorkRequest) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *WorkRequest) GetCancel() bool {
	if x != nil {
		return x.Cancel
	}
	return false
}

func (x *WorkRequest) GetVerbosity() int32 {
	if x != nil {
		return x.Verbosity
	}
	return 0
}

func (x *WorkRequest) GetSandboxDir() string {
	if x != nil {
		return x.SandboxDir
	}
	return ""
}

// The worker sends this message to Blaze when it finished its work on the
// WorkRequest message.
type WorkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Output message for this work unit.
	// This is akin to the combined stdout/stderr if the work unit were executed
	// as a standalone process. Output pertaining to a work unit should be
	// reported here instead of through the stdout/stderr of the worker process.
	// Assumed to be UTF-8 encoded.
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// This field must be set to the same request_id as the WorkRequest it is a
	// response to. Since worker processes which support multiplex worker will
	// handle multiple WorkRequests in parallel, this ID will be used to
	// determined which WorkerProxy does this WorkResponse belong to.
	RequestId int32 `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// EXPERIMENTAL When true, indicates that this response was sent due to
	// receiving a cancel request. The exit_code and output fields should be empty
	// and will be ignored. Exactly one WorkResponse must be sent for each
	// non-cancelling WorkRequest received by the worker, but if the worker
	// received a cancel request, it doesn't matter if it replies with a regular
	// WorkResponse or with one where was_cancelled = true.
	WasCancelled bool `protobuf:"varint,4,opt,name=was_cancelled,json=wasCancelled,proto3" json:"was_cancelled,omitempty"`
}

func (x *WorkResponse) Reset() {
	*x = WorkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_worker_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResponse) ProtoMessage() {}

func (x *WorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResponse.ProtoReflect.Descriptor instead.
func (*WorkResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *WorkResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *WorkResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *WorkResponse) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *WorkResponse) GetWasCancelled() bool {
	if x != nil {
		return x.WasCancelled
	}
	return false
}

var File_proto_worker_protocol_proto protoreflect.FileDescriptor

var file_proto_worker_protocol_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a,
	0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69,
	0x67, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65,
	0x73, 0x74, 0x22, 0xc1, 0x01, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x1e, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x06, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x65, 0x72, 0x62, 0x6f,
	0x73, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x76, 0x65, 0x72, 0x62,
	0x6f, 0x73, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x5f, 0x64, 0x69, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x44, 0x69, 0x72, 0x22, 0x87, 0x01, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x77,
	0x61, 0x73, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x77, 0x61, 0x73, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64,
	0x42, 0x34, 0x0a, 0x24, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x64,
	0x65, 0x76, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x6c, 0x69,
	0x62, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_worker_protocol_proto_rawDescOnce sync.Once
	file_proto_worker_protocol_proto_rawDescData = file_proto_worker_protocol_proto_rawDesc
)

func file_proto_worker_protocol_proto_rawDescGZIP() []byte {
	file_proto_worker_protocol_proto_rawDescOnce.Do(func() {
		file_proto_worker_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_worker_protocol_proto_rawDescData)
	})
	return file_proto_worker_protocol_proto_rawDescData
}

var file_proto_worker_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_worker_protocol_proto_goTypes = []any{
	(*Input)(nil),        // 0: Input
	(*WorkRequest)(nil),  // 1: WorkRequest
	(*WorkResponse)(nil), // 2: WorkResponse
}
var file_proto_worker_protocol_proto_depIdxs = []int32{
	0, // 0: WorkRequest.inputs:type_name -> Input
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_worker_protocol_proto_init() }
func file_proto_worker_protocol_proto_init() {
	if File_proto_worker_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_worker_protocol_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_worker_protocol_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WorkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_worker_protocol_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*WorkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_worker_protocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_worker_protocol_proto_goTypes,
		DependencyIndexes: file_proto_worker_protocol_proto_depIdxs,
		MessageInfos:      file_proto_worker_protocol_proto_msgTypes,
	}.Build()
	File_proto_worker_protocol_proto = out.File
	file_proto_worker_protocol_proto_rawDesc = nil
	file_proto_worker_protocol_proto_goTypes = nil
	file_proto_worker_protocol_proto_depIdxs = nil
}
